### ISSUE TITLE
Title Attribute for Diagrams

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fwprofile-editor-pub#2]
Diagrams have names which also appear on the "Global Property" panel of the diagram. I often find that the diagram names are short alphanumeric strings and are therefore not very descriptive. I would like to have a "Title" attribute for diagrams where I can put a brief description of a diagram.

At present, I put the diagram title in a note but perhaps we should make the title an attribute of a diagram and should show it on the diagram's "Global Property" panel.

As an example, the name of a diagram might be something like: "UpdRamMem" and its title might be something like: "Update RAM Memory".

**Comment by Tomas-M** [comment]
It is not a problem to add title, but I have some questions.
I was always thinking about the diagram name as a human readable text, thus I would expect the "Name" to be "Update RAM Memory" right away, and the editor would output code with files such as "UpdateRAMMemory.h" and so on.

I am not sure why you keep using names such as UpdRamMem, and then need a title to better understand your own names. Is there any reason for this at the first place? :-)

**Comment by pasetti** [comment]
In fact, there is no really good reason but it is simply the way things have evolved (at least for myself): I like to have short names because they normally become names of files and I do not like file names which are too long (and I must confess that I had not realized that I could have spaces in the name field!) but I also need some understandable text which typically is about 50 to 100 characters.

I would say that if the change can be done without too much difficulty and without adding too much complexity, we should do it. Otherwise, we can drop it.

**Comment by Tomas-M** [comment]
My concern is only regarding user experience, technically it is trivial.
Implemented by a7bc583c8660444f1d90fb52cb04e320e7fd9121

I can see I'm continuing my changes to the autocomplete branch, sorry about that.
To be honest I do not know how to split that into a different branch now, if it is even possible, I do not use git so much.
Perhaps we should merge the autocomplete branch to main now and continue on main.

**Comment by pasetti** [comment]
Thanks, Tomas.
I am not much of a git expert either but I think that it is fine if you continue on the autocomplete branch. 
I am still finalizing one issue where I would appreciate your opinion on technical feasibility. You will see it in 15-20 minutes.

You do not need to worry about the merge: I will do it when we are finished with the changes (I will also increase the version number).

**Comment by Tomas-M** [comment]
ok
