### ISSUE TITLE
Indentation in Diagram Notes

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fwprofile-editor-pub#3]
For some reason, it is not possible to have leading spaces in the text in the notes. For instance, if I write the following text in a note:

![image](https://user-images.githubusercontent.com/15838404/115621457-d5598380-a2f6-11eb-80e1-bba80f2008d5.png)

What I see in the main panel of the editor is this:

![image](https://user-images.githubusercontent.com/15838404/115621498-e4d8cc80-a2f6-11eb-89e3-4fffc3cfa36c.png)

Thus, it seems that the indentation at the start of a line is lost. Is there a special reason for this? Is there a way to keep the indentation?

**Comment by Tomas-M** [comment]
This is how SVG text is handled, it does not preserve whitespacs. There is a possibility to force it to preserve whitespace.
I made it for Notes only now by this commit: 749d8b9a68b0d9a6852651a4d19e00505e7378a3
If you like, I can make it the same way for all text elements (remember this breaks backward compatibility, if you have some whitespace in your existing states or notes, they would all be affecteed and would start showing in a new way)

**Comment by pasetti** [comment]
Thank you. I think that we only need the feature for the "note" element. Everything else looks fine as it is.
