### ISSUE TITLE
TC Parameters

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fwprofile-editor-pub#5]
This is a difficult issue and I cannot think of a good solution yet but the problem is (more or less) as follows.

Telecommands (items starting with "#TC") represent commands which can be sent to an application. A telecommand can have parameters. In the SCOS database base, the parameters are defined in this way:

- The command is defined in table CCF: its unique identifier is in field CNAME of this table.
- The list of parameters associated to a command is defined in table CDF: field CNAME of this table holds the identifier of a command and field PNAME holds the identifier of a parameter of the command
- The characteristics of each parameter are defined in table CPC: field PNAME holds the identifier of a command parameter and field DESCR holds a human-readable name of the parameter

To illustrate, consider the following example:

- In table CCF, we find command #TC(3,1) whose unique identifier is DPC70001
- In table CDF, we find four entries corresponding DPC70001. Each entry is a parameter of TC(3,1). The unique identifiers of the two parameters are: DPP70001 to DPP70004
- In table CPC, we finally find the human-readable names of the four telecommand parameters: DPU_IFSW_Sid, DPU_IFSW_Period, DPU_IFSW_NoDataItemId and DPU_IFSW_DataItemId

The need now is for the user to be able to define the value of the parameters of a command. For instance, a user might have a diagram where he is using telecommand #TC(3,1) and he would like to express the fact that he wants parameter DPU_IFSW_Sid to be equal to "HK_BASIC" and parameter DPU_IFSW_Period to be equal to 1. The other two parameters instead remain open. 

To make things simpler we can make the following assumptions:
- Parameter values are always expressed as strings
- Parameters can only be defined if the TC item is defined in an action or guard (if it is defined in a "note" element, then there is no need to define its parameters)
- A guard or an action can only contain one TC item

I am not sure what is the best way to let users define the TC parameters ... 

Suppose that we have a node N1 with a #TC(x,y) element. Here are two options of how the parameters for TC(x,y) might be defined:
- The parameters are defined in "run code" element: the user starts typing #TcPar and the autocompletion menu proposes the parameters associated to the TC(x,y)
- The user creates a note with a connector to node N1 and then he starts typing #TcPar in the note and the autocompletion menu proposes the parameters associated to the TC(x,y)

I would appreciate Tomas's feedback on the above problem!

**Comment by Tomas-M** [comment]
I am not sure what is the end goal here.
User should be able to see and select parameters, and when he is done, what should he see in a Description box for example? Or what should he see on the diagram? An image would help, even hand-drawn one. Thank you

**Comment by pasetti** [comment]
Here is an example of what it might look like if we use the first of the two solutions (the parameters appear in the "run-code" element and are only visible when the element is selected):
![image](https://user-images.githubusercontent.com/15838404/115697295-ba712880-a363-11eb-9f22-429136fa3929.png)

And here is another example of what it might look like if we use the second of the two solutions (the parameters appear in a node connected to the node):
![image](https://user-images.githubusercontent.com/15838404/115697678-0b811c80-a364-11eb-9bc1-45ddc4c8f09d.png)

I am not sure what is better or if there are still other solutions

**Comment by pasetti** [comment]
You are right: I am now moving away from the original intent of the tool. Maybe, I should fork the project and have a second tool which is really aimed at flight procedures with TCs and TMs. This means using the current editor as a starting point but then customizing it for the specific purposes of creating flight procedures. I will do some thinking on my side, too.

> Or do you put it there just because there is no other suitable place for that?
Yes, I put it there because I could not think of a better place

>  assume that when you type in "#TcPar" text, you expect to get autocompletions only the telecommand #TC(3,1) mentioned in Description field, right?
Yes

> Can you perhaps accept to get simply autocompletions of parameters for all possible telecommands, regardless of context?
This would not really work as there would too many parameters

**Comment by pasetti** [comment]
This issue actually belongs to the FCP Editor and has become obsolete after the latest round of updates to the FCP Editor.
