### ISSUE TITLE
key was too long; max key length is 1000

### ISSUE THREAD

**Issue by duchonic** [pnp-software/fwprofile-editor-pub#7]
Tested with wsl (windows subsystem for linux)

`sudo apt install php`
`sudo apt install mysql-server`
`sudo service mysql start`
...
calling install.php i got this:
```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VARCHAR(3000)' at line 1
mysql> [Fri Sep 24 16:40:03 2021] 127.0.0.1:53582 Accepted
[Fri Sep 24 16:40:03 2021] PHP Notice:  Fatal error: The query CREATE TABLE IF NOT EXISTS diagrams (
   id int(10) unsigned NOT NULL AUTO_INCREMENT,
   userID int(10) unsigned NOT NULL,
   name varchar(255) NOT NULL,
   isEmpty enum('N','Y') NOT NULL DEFAULT 'N',
   editorType varchar(255) NOT NULL,
   lastUpdate datetime NOT NULL,
   fwprop mediumtext NOT NULL,
   svg mediumtext NOT NULL,
   width int(10) unsigned NOT NULL,
   height int(10) unsigned NOT NULL,
   PRIMARY KEY (id),
   KEY name (name,userID),
   KEY userID (userID)
   ) ENGINE=MyISAM  has generated error Specified key was too long; max key length is 1000 bytes in /mnt/c/work/directory/work/wika/fwprofile-editor-pub/inc_db.php on line 54
[Fri Sep 24 16:40:03 2021] 127.0.0.1:53582 [200]: GET /install.php
```

I removed all the ENGINE=MyISAM and got it done.
First tests running with the webeditor (just statemachines) seems to work.

**Comment by Tomas-M** [comment]
Thank you for the feedback. 
I think that your error was caused not by the engine defined, but it seems to me that your default COLLATION is perhaps UTF8-something, which causes the 'name' key on your configuration to use more than 1000 bytes per key, which the MyISAM engine cannot handle.

Anyway, the ENGINE declaration was there for some historical reasons only, and I see no longer the need to keep it there, thus I've removed it in source code. 

Fixed here: c56880c4589f294c20b4f77c4a1a27a93567271d
