### ISSUE TITLE
Model Save Operation Fails Silently

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fwprofile-editor-pub#8]
I have made an installation of the editor on a server. The editor is accessed from an address like: https://www.xyz.com/fwprofile/. I have defined several models in the editor but I now have a non-nominal behaviour when I try to update the models. Here is what happens:

(1) I load a model and make the changes in my browser
(2) When I have completed the changes, I save the model
(3) The save operation appears to be successful
(4) However, when, at a later time and after having edited other models, I re-load the model I edited at point (1), I find that the changes I made at point (1) are no longer present
(5) Inspection of `/var/log/apache2/errors.log` shows that the save operation done at point (2) gave rise to the following error message:

`[Fri Oct 15 22:09:21.599430 2021] [php7:warn] [pid 129045] [client 217.236.113.233:48674] PHP Warning:  Unknown: Failed to write session data using user defined save handler. (session.save_path: /var/lib/php/sessions) in Unknown on line 0, referer: https://www.xyz.com/fwprofile/`

(6) If I then log out and close the browser tag with the editor and then open a new browser tag and log back into the editor, the changes I had made at point (1) appear to have been saved!!!!

This behaviour is in my view non-nominal but it might be due to a server configuration issue because I do not recall observing it on the "official" deployment of the FW Profile Editor at: `www.pnp-software.com/fwprofile/editor`.

**Comment by pasetti** [comment]
Actually, I have just been able to reproduce the behaviour described in this ticket also on the "official" FW Profile Editor installation at: www.pnp-software.com/fwprofile/editor. This happened while I was investigating the anomaly reported in ticket #9. I wonder whether the two anomalies (the one reported in this ticket and the one reported in ticket #9) are related ...

**Comment by pasetti** [comment]
I have updated the description of anomaly in the first update of the ticket. Let me know if it is clear. I should mention again that I suspect that this anomaly is related to the anomaly of ticket #9. I will test the change you proposed for that ticket later in the day and will let you know whether it fixes the issue.

**Comment by Tomas-M** [comment]
This should not be related to #9
I tried the following:
1) open https://www.pnp-software.com/fwprofile/editor/
2) login
3) load a state machine diagram, make changes, save it using COMMIT button or SAVE button
4) load another state machine diagram, make no changes
5) load again the first state machine diagram, I can see the saved changes properly

So I am afraid I cannot reproduce the problem.

The error log you mentioned is strange, it says that it is unable to save session data, which should not be related to this problem either IMHO. Strange

**Comment by pasetti** [comment]
The reason I suspect that the problem is related to #9 is that the anomalous behaviour described in this ticket only appears **after** there has been an import failure. In other words, I suggest you modify your test procedure as follows:

1)    open https://www.pnp-software.com/fwprofile/editor/
2)    login
2.1) go to "presets"-->"new procedure" and then import a new model
2.2) save the newly imported model and then go again to "presets"-->"new procedure" and import another model
2.3) I expect that the second import procedure will fail  
3)    load a state machine diagram, make changes, save it using COMMIT button or SAVE button
4)    load another state machine diagram, make no changes
5)    load again the first state machine diagram, I can see the saved changes properly

I could of course be wrong in seeing a relationship between the two issues but maybe we should first concentrate in the anomlay of ticket #9 because that one is easier to reproduce.
